<?php
$data = array (
  0 => 
  array (
    'cat_id' => '25',
    'cat_name' => '经销商下面的图片',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '6',
    'aricle_num' => '0',
  ),
  1 => 
  array (
    'cat_id' => '15',
    'cat_name' => '装修效果',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '6',
    'aricle_num' => '0',
  ),
  2 => 
  array (
    'cat_id' => '1',
    'cat_name' => '系统分类',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => '系统保留分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  3 => 
  array (
    'cat_id' => '32',
    'cat_name' => '活动专题',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '用户发布新的活动',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  4 => 
  array (
    'cat_id' => '22',
    'cat_name' => '加入吉采',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  5 => 
  array (
    'cat_id' => '33',
    'cat_name' => '直销店招商',
    'cat_type' => '1',
    'keywords' => '直销店招商',
    'cat_desc' => '直销店招商',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  6 => 
  array (
    'cat_id' => '23',
    'cat_name' => '新闻动态',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '25',
  ),
  7 => 
  array (
    'cat_id' => '24',
    'cat_name' => '公司公告',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '34',
  ),
  8 => 
  array (
    'cat_id' => '2',
    'cat_name' => '网店信息',
    'cat_type' => '3',
    'keywords' => '',
    'cat_desc' => '网店信息分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '4',
  ),
  9 => 
  array (
    'cat_id' => '3',
    'cat_name' => '网店帮助分类',
    'cat_type' => '4',
    'keywords' => '',
    'cat_desc' => '网店帮助分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '6',
    'aricle_num' => '0',
  ),
  10 => 
  array (
    'cat_id' => '13',
    'cat_name' => '公司信息',
    'cat_type' => '5',
    'keywords' => '公司简介',
    'cat_desc' => '公司简介',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  11 => 
  array (
    'cat_id' => '5',
    'cat_name' => '购物指南',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '4',
  ),
  12 => 
  array (
    'cat_id' => '7',
    'cat_name' => '配送方式',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '配送方式',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  13 => 
  array (
    'cat_id' => '8',
    'cat_name' => '服务保证 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '付款方式',
    'cat_type' => '5',
    'keywords' => '付款方式',
    'cat_desc' => '付款方式',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  15 => 
  array (
    'cat_id' => '10',
    'cat_name' => '会员中心',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '欧式风格',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '15',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '美式风格',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '15',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '中国风格',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '15',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '日式风格',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '15',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '非洲风格',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '15',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '英式风格',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '15',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  22 => 
  array (
    'cat_id' => '26',
    'cat_name' => '综合',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '25',
    'has_children' => '0',
    'aricle_num' => '6',
  ),
  23 => 
  array (
    'cat_id' => '27',
    'cat_name' => '样板',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '25',
    'has_children' => '0',
    'aricle_num' => '6',
  ),
  24 => 
  array (
    'cat_id' => '28',
    'cat_name' => '商品',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '25',
    'has_children' => '0',
    'aricle_num' => '6',
  ),
  25 => 
  array (
    'cat_id' => '29',
    'cat_name' => '广告',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '25',
    'has_children' => '0',
    'aricle_num' => '6',
  ),
  26 => 
  array (
    'cat_id' => '30',
    'cat_name' => '特价',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '25',
    'has_children' => '0',
    'aricle_num' => '6',
  ),
  27 => 
  array (
    'cat_id' => '31',
    'cat_name' => '专题',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '25',
    'has_children' => '0',
    'aricle_num' => '7',
  ),
);
?>